[package]
name = "solution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adventage = "0.2.1"
intcode = { version = "0.1.0", path = "../intcode" }
