[package]
name = "aoc-2015-4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adventage = "0.3.0"
md5 = "0.7.0"
