[package]
name = "solution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adventage = { version = "0.1.0", path = "../../../adventage/adventage" }
md5 = "0.7.0"
