[package]
name = "aoc-2019-17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adventage = "0.3.0"
intcode = { version = "0.1.0", path = "../intcode" }
